version: '3.8'

services:
  app:
    build: .
    container_name: globant-task-app
    ports:
      - "8080:8080"
    command: >
      sh -c 'prisma validate && prisma generate && prisma db push && uvicorn app.main:app --host 0.0.0.0 --port 8080 --log-level info --reload'
    volumes:
      - ./app:/globant-task/app
      - ./data:/globant-task/data

  worker:
    build: .
    command: >
      sh -c 'prisma validate && prisma generate && celery --app app.celery.worker worker --loglevel=info'
    volumes:
      - ./app:/globant-task/app
      - ./data:/globant-task/data
    depends_on:
      - app
    deploy:
      mode: replicated
      replicas: 1

  flower:
    build: .
    container_name: globant-task-flower
    command: celery --broker=${CELERY_BROKER_URL} flower --port=5555
    env_file:
      - .env
    ports:
      - "5555:5555"

  prisma-studio:
    build: .
    container_name: globant-task-prisma-studio
    command: prisma studio --schema=./schema.prisma --browser none --port 5556
    ports:
      - "5556:5556"
    volumes:
      - ./app:/globant-task/app
      - ./data:/globant-task/data
