version: '3.8'

services:

  postgres:
    image: postgres:14.1-alpine
    container_name: globant-task-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=globant
    ports:
      - 5432:5432

  redis:
    image: redis:7

  app:
    build: .
    ports:
      - 8080:8080
    command: sh -c 'prisma validate && prisma generate && prisma db push && uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload'
    volumes:
      - ./app:/globant-task/app
      - ./data:/globant-task/data
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - postgres

  worker:
    build: .
    command: sh -c 'prisma validate && prisma generate && prisma db push && celery --app app.celery.worker worker --loglevel=debug'
    volumes:
      - ./app:/globant-task/app
      - ./data:/globant-task/data
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - app
      - redis
#    deploy:
#      mode: replicated
#      replicas: 2

  flower:
    build: .
    command: celery --broker=redis://redis:6379/0 flower --port=5555
    ports:
      - 5555:5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis